# This is a basic workflow to help you get started with Actions stock

name: CI

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Rimuovi la 'v' dalla versione
        id: preprocess_version
        run: |
          VERSION=1.1.1
          echo "VERSION=${VERSION//v/}" >> $GITHUB_ENV
      
      - name: Usa la versione modificata
        run: echo "La versione è $VERSION"

