# This is a basic workflow to help you get started with Actions stock

name: CI

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Rimuovi la 'v' dalla versione
        run: echo VERSION=$(echo ${GITHUB_REF#refs/tags/}) >> $GITHUB_ENV
      - name: Usa la versione modificata
        run: echo "La versione è $VERSION"

