# This is a basic workflow to help you get started with Actions stock

name: Check Release Tag Name

on:
  release:
    types: [published]

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Check Tag Name
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}
        REGEXP: '^v[0-9]+\.[0-9]+\.[0-9]+$' # Modifica questa regexp come necessario
      run: |
        if [[ "$TAG_NAME" =~ $REGEXP ]]; then
          echo "Il tag matcha con la regexp."
          # Aggiungi qui ulteriori azioni se la regexp corrisponde
        else
          echo "Il tag non matcha con la regexp."
          # Opzionalmente, puoi fallire il workflow se non c'è match
          exit 1
        fi
