# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    types:
      - opened

jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event_name != 'pull_request' || '! github.event.pull_request.draft')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Branch
        id: branch
      #  run: echo "version=${TAG}" >> $GITHUB_OUTPUT
      #  run: echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        run: echo "version=${{ github.event.pull_request.draft }}" >> $GITHUB_OUTPUT
      #  env:
      #    TAG: ${{ github.event.release.tag_name }}
      - name: Build base image
        run: |
          echo $VERSION
        env:
          VERSION: ${{ steps.branch.outputs.version }}
