# This is a basic workflow to help you get started with Actions stock

name: Check Release Tag Name

on:
  push:
    branches:
      - master

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Rimuovi la 'v' dalla versione
        id: set_version
        run: echo "::set-output name=version::$(echo 'v1.1.1' | sed 's/^v//')"
      
      - name: Usa la versione modificata
        run: echo "La versione è ${{ steps.set_version.outputs.version }}"

